### ISSUE TITLE
Invalid block type: Cardgate\Payment\Block\Form\DefaultForm

### ISSUE THREAD

**Issue by mikebranderhorst** [cardgate/magento2#10]
When trying to add a product to a new order in the backend the ajax POST call returns a 500 error with 2 exception(s):

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: Cardgate\Payment\Block\Form\DefaultForm

Exception #1 (ReflectionException): Class Cardgate\Payment\Block\Form\DefaultForm does not exist

The block Cardgate\Payment\Block\Form\DefaultForm does not exist in the module.

vendor/cardgate/magento2/Model/PaymentMethods.php
line 52
protected $_formBlockType = 'Cardgate\Payment\Block\Form\DefaultForm';

**Comment by cardgate** [comment]
This problem should be fixed with release v2.0.10 published a minute ago. Thank you for reporting.
