### ISSUE TITLE
Reverted bug fix

### ISSUE THREAD

**Issue by SanderAtom** [cardgate/magento2#12]
He I see you reverted my [bugfix](https://github.com/cardgate/magento2/pull/8), could you add it back again?

**Comment by cardgate** [comment]
Unfortunately no, not in it's current form. If I apply the patch I'm getting those same error messages as in your other reported issue: "Payment model name is not provided in config", which happens because with your patch the preprocessor is never invoked.

**Comment by cardgate** [comment]
See my last comment: https://github.com/cardgate/magento2/issues/9
