### ISSUE TITLE
Fix for payments that are stuck on pending

### ISSUE THREAD

**Issue by ghost** [cardgate/magento2#15]
The following issue was reported for the new Magento 2.2.6 release:
https://github.com/magento/magento2/issues/18148

Has this issue been fixed in de Cardgate extension?

**Comment by cardgate** [comment]
Unfortunately, this [issue](https://github.com/magento/magento2/issues/18148) affects our payment modules as well.
We advise customers to NOT update to Magento 2.2.6, as we await a solution from Magento.

**Comment by cardgate** [comment]
This issue has been fixed in version 2.0.28 of our module.
