### ISSUE TITLE
Billing address form not available for Cardgate payment methods

### ISSUE THREAD

**Issue by paulvandermeijs** [cardgate/magento2#19]
### Steps to reproduce:

1. Use clean install of Magento.
2. Install CardGate module following the steps from https://github.com/cardgate/magento2/blob/master/README.mdown#installation
3. Setup CardGate payment methods.
4. Add product to cart and go to checkout.
5. Default Magento payment methods show form for billing address but CardGate methods only show _Place Order_ button

![screen shot 2019-02-26 at 13 15 39](https://user-images.githubusercontent.com/513046/53413479-5abda380-39cc-11e9-85f8-7a7dc47c81a0.png)

![screen shot 2019-02-26 at 13 15 57](https://user-images.githubusercontent.com/513046/53413487-601aee00-39cc-11e9-8f7f-52e8ba13c990.png)

### Test environment:
Magento Version: 2.2.6 and 2.2.7
CardGate Module for Magento 2: 2.0.19

**Comment by cardgate** [comment]
We confirm this issue under the following conditions:
The Display Billing Address option of the Checkout Options of Magento is set to the Payment Method option.
When this is set to the Payment Page option it functions as expected.

**Comment by cardgate** [comment]
This issue is fixed in version 2.0.20.
