### ISSUE TITLE
Checkout Agreement Payload is missing

### ISSUE THREAD

**Issue by mikebranderhorst** [cardgate/magento2#5]
'Magento_CheckoutAgreements/js/model/agreements-assigner'

https://github.com/cardgate/magento2/blob/master/view/frontend/web/js/action/set-payment-information.js

https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/CheckoutAgreements/view/frontend/web/js/model/set-payment-information-mixin.js

**Comment by cardgate** [comment]
Can you elaborate on the issue? What specific error message are you seeing or what parts of the plugin aren't functioning as you'd expect?
In addition, we've released a beta release yesterday with improvements to the agreements part of the checkout page. Could you perhaps see if this beta release fixes the issue for you?
Thanks for reporting.

**Comment by mikebranderhorst** [comment]
Magento 2.1.10 plugin 2.0.6

In the checkout when you click a payment method there is an ajax call with an 400 (Bad Request)

/rest/default/V1/carts/mine/set-payment-information

When you check the payload in the POST the checkout agreement is missing.

{"cartId":"12345","paymentMethod":{"method":"cardgate_creditcard"},"billingAddress":{"customerAddressId":"123","countryId":"NL","regionCode":null,"region":null,"customerId":"1234","street":["Street ","1","A"],"telephone":"+31234567890","postcode":"1234 AB","city":"City","firstname":"First","lastname":"Last","saveInAddressBook":null}}

**Comment by cardgate** [comment]
This problem should be fixed with version 2.0.7.
Thank you for reporting.
