### ISSUE TITLE
Automated tests impossible by undefined constant BP

### ISSUE THREAD

**Issue by mikebranderhorst** [cardgate/magento2#6]
https://github.com/cardgate/magento2/blob/master/registration.php

$vendorDir = require BP . '/app/etc/vendor_path.php';
$vendorAutoload = BP . "/{$vendorDir}/autoload.php";

The constant BP is defined within app/autoload.php

vendor/bin/grumphp runs from:

$autoloadLocations = [
    getcwd() . '/vendor/autoload.php',
    getcwd() . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
];

BP is not defined resulting in errors when using git hook check code etc.

Notice: Use of undefined constant BP - assumed 'BP' in vendor/cardgate/magento2/registration.php on line 13

**Comment by cardgate** [comment]
Thank you for reporting.
Could you try to remove lines 13 till the end and see if that fixes your problem?
Or maybe install the beta release, which also changes the way the autoloading of classes is handled.

**Comment by cardgate** [comment]
The offending constant has been removed from the source files in version 2.0.7.
