### ISSUE TITLE
After deploying module the checkout crashes if settings not saved in backend

### ISSUE THREAD

**Issue by mikebranderhorst** [cardgate/magento2#7]
After installing the module with composer and deploying to test/staging/production the checkout crashes! On production this will display a Report page. After saving the module config for the first time in the backend the checkout works fine. It seems the module needs settings before initial config save in backend.

Magento 2.1.10 Module 2.0.6

**Comment by cardgate** [comment]
This should be solved with version 2.0.7 of the plugin.
Thank you for reporting.
